import { AlertTriangle, BookOpen, CheckCircle2, Clock3, Play, Target } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Badge, Button, Card, Content, EmptyState, ErrorState, KPICard, LoadingState, Section } from '@/design-system';
import { useToday } from '@/today/hooks';
import type { TodayData, TodayStatus } from '@/today/types';

const labels = { study: 'Estudo', questions: 'Questoes', review: 'Revisao', mockExam: 'Simulado', reading: 'Leitura', high: 'Alta', medium: 'Media', low: 'Baixa' };

export function TodayView({ data, onNavigate, status }: { data: TodayData; onNavigate?: (route: string) => void; status: TodayStatus }) {
  if (status === 'loading') return <Content><LoadingState label="Carregando plano de hoje" /></Content>;
  if (status === 'error') return <ErrorState title="Nao foi possivel carregar seu dia" description="Tente novamente em alguns instantes." />;
  if (status === 'empty') return <Content><EmptyState title="Registre seus primeiros dados" description="Registre estudos ou questoes para montar um plano mais preciso." icon={BookOpen} /></Content>;
  if (status === 'completed') return <Content><EmptyState title="Dia concluido" description="Voce concluiu todas as atividades planejadas." icon={CheckCircle2} /></Content>;
  return <Content className="space-y-8">
    <Section className="rounded-md border border-app-border bg-white p-6 shadow-panel"><Badge tone="blue">Hoje</Badge><h1 className="mt-3 text-3xl font-bold text-app-text">{data.greeting}</h1><p className="mt-2 text-app-muted">{data.motivation}</p></Section>
    <section className="grid gap-4 md:grid-cols-3"><KPICard icon={Clock3} label="Tempo do plano" helper={`${data.remainingMinutes} min restantes`} progress={data.availableMinutes ? Math.round((data.plannedMinutes / data.availableMinutes) * 100) : 0} tone="blue" value={`${data.plannedMinutes} min`} /><KPICard icon={Target} label="Indice de preparacao" helper={data.preparationMessage} tone="green" value={data.preparationIndex ? `${data.preparationIndex}%` : 'Em formacao'} /><KPICard icon={CheckCircle2} label="Meta da semana" helper={`${data.weeklyStudiedHours}h de ${data.weeklyGoalHours}h`} progress={Math.round((data.weeklyStudiedHours / data.weeklyGoalHours) * 100)} tone="amber" value={`${data.weeklyStudiedHours}h`} /></section>
    <Section className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><Card className="p-0"><div className="border-b border-app-border p-5"><h2 className="text-xl font-bold text-app-text">Plano do dia</h2><p className="mt-1 text-sm text-app-muted">Priorizacao e ordem definidas pelo Decision Engine.</p></div><div className="space-y-3 p-5">{data.activities.map((activity) => <div className="flex flex-col gap-3 rounded-md border border-app-border p-4 sm:flex-row sm:items-center" key={activity.id}><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><Badge tone={activity.priority === 'high' ? 'red' : activity.priority === 'medium' ? 'amber' : 'blue'}>{labels[activity.priority]}</Badge><Badge tone="slate">{labels[activity.type]}</Badge></div><h3 className="mt-2 font-semibold text-app-text">{activity.discipline}: {activity.subject}</h3><p className="mt-1 text-sm text-app-muted">{activity.estimatedMinutes} min - {activity.recommendationReason}</p></div><Button icon={<Play aria-hidden="true" className="h-4 w-4" />} onClick={() => onNavigate?.(activity.actionRoute ?? '/estudos')}>{activity.actionLabel ?? 'Comecar'}</Button></div>)}</div></Card><div className="space-y-5"><Card><h2 className="font-bold text-app-text">Proxima revisao</h2><p className="mt-3 text-lg font-semibold">{data.nextReview.discipline}</p><p className="text-sm text-app-muted">{data.nextReview.subject}</p><p className="mt-4 font-semibold text-app-primary">{data.nextReview.time ? `Hoje, ${data.nextReview.time} - ${data.nextReview.estimatedMinutes} min` : 'Nenhuma revisao para hoje'}</p></Card><Card><h2 className="font-bold text-app-text">Questoes recomendadas</h2><p className="mt-3 text-2xl font-bold">{data.recommendedQuestions.quantity} questoes</p><p className="text-sm text-app-muted">{data.recommendedQuestions.reason}</p><Button className="mt-4 w-full" variant="secondary" onClick={() => onNavigate?.('/questoes')}>Resolver agora</Button></Card></div></Section>
    <Section className="grid gap-6 lg:grid-cols-2"><Card><h2 className="font-bold text-app-text">O que melhorar nesta semana</h2><div className="mt-4 space-y-3">{data.recommendations.map((item) => <div className="rounded-md border border-app-border p-4" key={item.id}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-app-text">{item.title}</p><p className="mt-1 text-sm text-app-muted">{item.problem}</p></div><Badge tone={item.urgency === 'high' ? 'red' : item.urgency === 'medium' ? 'amber' : 'blue'}>{labels[item.urgency]}</Badge></div><p className="mt-3 text-sm text-app-muted">{item.evidence}</p><p className="mt-2 text-sm text-app-muted">{item.impact}</p><div className="mt-3 flex items-center justify-between gap-3"><span className="text-sm font-medium text-app-text">{item.estimatedMinutes} min estimados</span><Button size="sm" variant="secondary" onClick={() => onNavigate?.(item.actionRoute)}>{item.actionLabel}</Button></div></div>)}{data.recommendations.length === 0 ? <p className="text-sm text-app-muted">Registre estudos e questoes para receber recomendacoes mais precisas.</p> : null}</div></Card><Card><h2 className="font-bold text-app-text">Resumo rapido</h2><div className="mt-4 grid grid-cols-2 gap-4 text-sm"><span>Questoes hoje<strong className="block text-lg">{data.quickSummary.answeredQuestions}</strong></span><span>Horas estudadas<strong className="block text-lg">{data.quickSummary.studiedHours}h</strong></span><span>Tempo restante<strong className="block text-lg">{data.quickSummary.remainingMinutes} min</strong></span><span>Taxa de acertos<strong className="block text-lg">{data.quickSummary.accuracyRate}%</strong></span></div><ul className="mt-5 space-y-2 border-t border-app-border pt-4">{data.alerts.map((alert) => <li className="flex gap-3 text-sm text-app-muted" key={alert}><AlertTriangle aria-hidden="true" className="h-5 w-5 shrink-0 text-app-warning" />{alert}</li>)}</ul></Card></Section>
  </Content>;
}
export function TodayPage() { const { data, status } = useToday(); const navigate = useNavigate(); return <TodayView data={data} onNavigate={navigate} status={status} />; }
