import { db } from '@/core/database/database';
import type { ScheduleItem } from '@/core/database/types';
import type { QuestionBlock } from '@/questions/types';
import type { ReviewRecord } from '@/reviews/types';
import type { StudySession } from '@/study/types';

export type AnalyticsPeriod = 'today' | '7d' | '30d' | 'all';
export interface DailyAnalyticsPoint { date: string; minutes: number; questions: number; accuracyRate: number; completedActivities: number; completedReviews: number; }
export interface DisciplineAnalytics { name: string; minutes: number; questions: number; accuracyRate: number; }
export interface PeriodComparison { current: number; previous: number; difference: number; percentage?: number; }
export interface AnalyticsResult {
  period: AnalyticsPeriod; totals: { minutes: number; sessions: number; questions: number; correct: number; wrong: number; annulled: number; accuracyRate: number; completedActivities: number; completedReviews: number; activeErrors: number; masteredErrors: number; disciplines: number; streak: number; };
  series: DailyAnalyticsPoint[]; disciplines: DisciplineAnalytics[]; comparison: { minutes: PeriodComparison; sessions: PeriodComparison; questions: PeriodComparison; accuracyRate: PeriodComparison; completedActivities: PeriodComparison; completedReviews: PeriodComparison; };
  planHealth: { withinWindow: number; completed: number; overdue: number; today: number; future: number; outsideWindow: number; remainingMinutes: number; overdueMinutes: number; minutesRequiredPerDay: number; };
}
const dateOnly = (value: string) => value.slice(0, 10);
const completed = (status: string) => status === 'completed' || status.toLowerCase().includes('conclu');
const addDays = (date: string, amount: number) => { const value = new Date(`${date}T00:00:00`); value.setDate(value.getDate() + amount); return dateOnly(value.toISOString()); };
const periodStart = (period: AnalyticsPeriod, today: string, records: string[]) => period === 'today' ? today : period === '7d' ? addDays(today, -6) : period === '30d' ? addDays(today, -29) : records.sort()[0] ?? today;
const compare = (current: number, previous: number): PeriodComparison => ({ current, previous, difference: current - previous, percentage: previous ? Math.round(((current - previous) / previous) * 100) : undefined });

export function calculateStudyAnalytics(args: { period: AnalyticsPeriod; now: string; examDate?: string; sessions: StudySession[]; blocks: QuestionBlock[]; schedule: ScheduleItem[]; reviews: ReviewRecord[]; errors: Array<{ status: string }>; }): AnalyticsResult {
  const today = dateOnly(args.now); const recordDates = [...args.sessions.map((item) => item.date), ...args.blocks.map((item) => item.date)]; const start = periodStart(args.period, today, recordDates);
  const inRange = (date: string) => date >= start && date <= today;
  const sessions = args.sessions.filter((item) => inRange(item.date)); const blocks = args.blocks.filter((item) => inRange(item.date));
  const totalMinutes = sessions.reduce((sum, item) => sum + item.durationMinutes, 0) + blocks.reduce((sum, item) => sum + item.durationMinutes, 0);
  const questions = sessions.reduce((sum, item) => sum + item.questionsAnswered, 0) + blocks.reduce((sum, item) => sum + item.totalQuestions, 0);
  const correct = sessions.reduce((sum, item) => sum + item.correctAnswers, 0) + blocks.reduce((sum, item) => sum + item.correctAnswers, 0);
  const wrong = sessions.reduce((sum, item) => sum + item.wrongAnswers, 0) + blocks.reduce((sum, item) => sum + item.wrongAnswers, 0);
  const annulled = blocks.reduce((sum, item) => sum + item.annulledAnswers, 0);
  const dates = [...new Set([...sessions.map((item) => item.date), ...blocks.map((item) => item.date)])].sort();
  const series: DailyAnalyticsPoint[] = dates.map((date) => { const dailySessions = sessions.filter((item) => item.date === date); const dailyBlocks = blocks.filter((item) => item.date === date); const dailyQuestions = dailySessions.reduce((sum, item) => sum + item.questionsAnswered, 0) + dailyBlocks.reduce((sum, item) => sum + item.totalQuestions, 0); const dailyCorrect = dailySessions.reduce((sum, item) => sum + item.correctAnswers, 0) + dailyBlocks.reduce((sum, item) => sum + item.correctAnswers, 0); return { date, minutes: dailySessions.reduce((sum, item) => sum + item.durationMinutes, 0) + dailyBlocks.reduce((sum, item) => sum + item.durationMinutes, 0), questions: dailyQuestions, accuracyRate: dailyQuestions ? Math.round((dailyCorrect / dailyQuestions) * 100) : 0, completedActivities: args.schedule.filter((item) => completed(item.status) && dateOnly(item.completedAt ?? item.updatedAt) === date).length, completedReviews: args.reviews.filter((item) => item.status === 'completed' && dateOnly(item.completedAt ?? item.updatedAt) === date).length }; });
  const groups = [...sessions, ...blocks].reduce<Record<string, { minutes: number; questions: number; correct: number }>>((acc, item) => { const name = 'disciplineName' in item ? item.disciplineName : item.discipline; const current = acc[name] ?? { minutes: 0, questions: 0, correct: 0 }; current.minutes += item.durationMinutes; current.questions += 'questionsAnswered' in item ? item.questionsAnswered : item.totalQuestions; current.correct += item.correctAnswers; acc[name] = current; return acc; }, {});
  const disciplines = Object.entries(groups).map(([name, value]) => ({ name, minutes: value.minutes, questions: value.questions, accuracyRate: value.questions ? Math.round((value.correct / value.questions) * 100) : 0 })).sort((a, b) => b.minutes - a.minutes);
  let streak = 0; for (let cursor = today; dates.includes(cursor); cursor = addDays(cursor, -1)) streak += 1;
  const rangeDays = Math.max(1, Math.round((new Date(`${today}T00:00:00`).getTime() - new Date(`${start}T00:00:00`).getTime()) / 86400000) + 1); const priorStart = addDays(start, -rangeDays); const priorEnd = addDays(start, -1);
  const priorSessions = args.sessions.filter((item) => item.date >= priorStart && item.date <= priorEnd); const priorBlocks = args.blocks.filter((item) => item.date >= priorStart && item.date <= priorEnd); const priorQuestions = priorSessions.reduce((sum, item) => sum + item.questionsAnswered, 0) + priorBlocks.reduce((sum, item) => sum + item.totalQuestions, 0); const priorCorrect = priorSessions.reduce((sum, item) => sum + item.correctAnswers, 0) + priorBlocks.reduce((sum, item) => sum + item.correctAnswers, 0);
  const currentCompleted = args.schedule.filter((item) => completed(item.status) && inRange(dateOnly(item.completedAt ?? item.updatedAt))).length; const priorCompleted = args.schedule.filter((item) => completed(item.status) && dateOnly(item.completedAt ?? item.updatedAt) >= priorStart && dateOnly(item.completedAt ?? item.updatedAt) <= priorEnd).length; const currentReviews = args.reviews.filter((item) => item.status === 'completed' && inRange(dateOnly(item.completedAt ?? item.updatedAt))).length; const priorReviews = args.reviews.filter((item) => item.status === 'completed' && dateOnly(item.completedAt ?? item.updatedAt) >= priorStart && dateOnly(item.completedAt ?? item.updatedAt) <= priorEnd).length;
  const inWindow = args.schedule.filter((item) => !item.outsideExamWindow); const overdue = inWindow.filter((item) => !completed(item.status) && item.plannedDate < today); const future = inWindow.filter((item) => !completed(item.status) && item.plannedDate > today); const todayItems = inWindow.filter((item) => !completed(item.status) && item.plannedDate === today); const remaining = inWindow.filter((item) => !completed(item.status)); const daysToExam = args.examDate ? Math.max(1, Math.ceil((new Date(`${args.examDate}T00:00:00`).getTime() - new Date(`${today}T00:00:00`).getTime()) / 86400000)) : 1;
  return { period: args.period, totals: { minutes: totalMinutes, sessions: sessions.length, questions, correct, wrong, annulled, accuracyRate: questions ? Math.round((correct / questions) * 100) : 0, completedActivities: currentCompleted, completedReviews: currentReviews, activeErrors: args.errors.filter((item) => item.status === 'active').length, masteredErrors: args.errors.filter((item) => item.status === 'mastered').length, disciplines: disciplines.length, streak }, series, disciplines, comparison: { minutes: compare(totalMinutes, priorSessions.reduce((sum, item) => sum + item.durationMinutes, 0) + priorBlocks.reduce((sum, item) => sum + item.durationMinutes, 0)), sessions: compare(sessions.length, priorSessions.length), questions: compare(questions, priorQuestions), accuracyRate: compare(questions ? Math.round((correct / questions) * 100) : 0, priorQuestions ? Math.round((priorCorrect / priorQuestions) * 100) : 0), completedActivities: compare(currentCompleted, priorCompleted), completedReviews: compare(currentReviews, priorReviews) }, planHealth: { withinWindow: inWindow.length, completed: inWindow.filter((item) => completed(item.status)).length, overdue: overdue.length, today: todayItems.length, future: future.length, outsideWindow: args.schedule.filter((item) => item.outsideExamWindow).length, remainingMinutes: remaining.reduce((sum, item) => sum + (item.actualMinutes ?? 45), 0), overdueMinutes: overdue.reduce((sum, item) => sum + (item.actualMinutes ?? 45), 0), minutesRequiredPerDay: Math.ceil(remaining.reduce((sum, item) => sum + (item.actualMinutes ?? 45), 0) / daysToExam) } };
}
export async function getLocalStudyAnalytics(period: AnalyticsPeriod, now = new Date().toISOString()): Promise<AnalyticsResult> { const [profiles, sessions, blocks, schedule, reviews, errors] = await Promise.all([db.contestProfiles.toArray(), db.studySessions.toArray(), db.questionBlocks.toArray(), db.scheduleItems.toArray(), db.reviews.toArray(), db.errorRecords.toArray()]); return calculateStudyAnalytics({ period, now, examDate: profiles[0]?.examDate, sessions: sessions as unknown as StudySession[], blocks: blocks as unknown as QuestionBlock[], schedule, reviews: reviews as unknown as ReviewRecord[], errors: errors as unknown as Array<{ status: string }> }); }
