import { errorBankMocks } from '@/error-bank/mocks'; import type { AnalyticsEngineErrorEvent, ErrorAction, ErrorBankFacts, ErrorBankStats, ErrorFilters, ErrorRecord, ErrorRecordInput, ErrorRecordValidationErrors, RecommendationEngineErrorFact, ReviewEngineErrorFact, TodayErrorSignal } from '@/error-bank/types';
export const defaultErrorFilters: ErrorFilters={discipline:'all',subject:'all',category:'all',priority:'all',status:'all',source:'all',query:'',recurringOnly:false,pendingOnly:false};
export function filterErrorRecords(records:ErrorRecord[],f:ErrorFilters){const q=f.query.toLowerCase();return records.filter(r=>(f.discipline==='all'||r.discipline===f.discipline)&&(f.subject==='all'||r.subject===f.subject)&&(f.category==='all'||r.category===f.category)&&(f.priority==='all'||r.priority===f.priority)&&(f.status==='all'||r.status===f.status)&&(f.source==='all'||r.source===f.source)&&(!f.recurringOnly||r.recurrence>1)&&(!f.pendingOnly||r.status==='active')&&(!q||`${r.discipline} ${r.subject} ${r.reason} ${r.tags.join(' ')}`.toLowerCase().includes(q)));}
export function calculateErrorStats(records:ErrorRecord[]):ErrorBankStats{const active=records.filter(r=>r.status==='active');const frequent=(key:keyof ErrorRecord)=>{const map=new Map<string,number>();records.forEach(r=>{const v=String(r[key]);map.set(v,(map.get(v)||0)+1)});return [...map].sort((a,b)=>b[1]-a[1])[0]?.[0]||'-'};return{active:active.length,recurring:records.filter(r=>r.recurrence>1).length,mastered:records.filter(r=>r.status==='mastered').length,pendingReview:active.length,predominantCategory:frequent('category'),criticalDiscipline:frequent('discipline')}}
export const emptyErrorRecordInput: ErrorRecordInput = { discipline:'', subject:'', category:'', context:'', reason:'', correctConcept:'', correctiveAction:'', priority:'', tags:'', notes:'', selectedAnswer:'', source:'Manual', nextReview:'', complementaryNotes:'' };
export function validateErrorRecord(input:ErrorRecordInput, today=new Date()):ErrorRecordValidationErrors{const errors:ErrorRecordValidationErrors={};(['discipline','subject','category','context','reason','correctConcept','correctiveAction','priority'] as const).forEach(k=>{if(!input[k].trim())errors[k]='Este campo e obrigatorio.'});if(input.nextReview){const review=new Date(`${input.nextReview}T00:00:00`);const start=new Date(today.getFullYear(),today.getMonth(),today.getDate());if(Number.isNaN(review.getTime()))errors.nextReview='Informe uma data valida.';else if(review<start)errors.nextReview='A revisao nao pode ser anterior a hoje.'}return errors}
export function createErrorRecord(input:ErrorRecordInput):ErrorRecord{return{id:`error-${Date.now()}`,discipline:input.discipline.trim(),subject:input.subject.trim(),category:input.category.trim(),priority:input.priority||'medium',status:'active',source:input.source.trim()||'Manual',question:input.context.trim(),selectedAnswer:input.selectedAnswer.trim()||'-',correctAnswer:input.correctConcept.trim(),explanation:input.correctConcept.trim(),reason:input.reason.trim(),correctiveAction:input.correctiveAction.trim(),recurrence:1,nextReview:input.nextReview,notes:[input.notes,input.complementaryNotes].filter(Boolean).join(' '),tags:input.tags.split(',').map(tag=>tag.trim()).filter(Boolean),history:['Registro manual criado'],createdAt:new Date().toISOString()}}
export function applyErrorAction(record:ErrorRecord,action:ErrorAction,date?:string):ErrorRecord{if(action==='review')return{...record,status:'reviewed',history:[...record.history,'Erro marcado como revisado.']};if(action==='master')return{...record,status:'mastered',history:[...record.history,'Assunto marcado como dominado.']};if(action==='archive')return{...record,status:'archived',history:[...record.history,'Erro arquivado.']};if(action==='recur')return{...record,recurrence:record.recurrence+1,status:'active',history:[...record.history,'Nova ocorrencia registrada.']};return{...record,nextReview:date||record.nextReview,history:[...record.history,'Revisao reagendada.']}}
export function createErrorBankFacts(records:ErrorRecord[]):ErrorBankFacts{return{activeErrors:records.filter(r=>r.status==='active').length,recurringErrorSubjects:records.filter(r=>r.recurrence>1).map(r=>r.subject),pendingReviewIds:records.filter(r=>r.status==='active').map(r=>r.id)}}
export const toReviewFact=(r:ErrorRecord):ReviewEngineErrorFact=>({errorId:r.id,subject:r.subject,nextReview:r.nextReview}); export const toRecommendationFact=(r:ErrorRecord):RecommendationEngineErrorFact=>({errorId:r.id,correctiveAction:r.correctiveAction}); export const toAnalyticsEvent=(r:ErrorRecord):AnalyticsEngineErrorEvent=>({errorId:r.id,category:r.category,recurrence:r.recurrence}); export const toTodaySignal=(r:ErrorRecord):TodayErrorSignal=>({errorId:r.id,correctiveAction:r.correctiveAction}); export const ErrorBankService={getRecords:()=>errorBankMocks,runAction:(record:ErrorRecord,action:ErrorAction,date?:string)=>applyErrorAction(record,action,date)};
