import { publishLocalDataChange } from '@/core/database/events';
import type { AnalyticsEngineErrorEvent, ErrorAction, ErrorBankFacts, ErrorBankStats, ErrorFilters, ErrorRecord, ErrorRecordInput, ErrorRecordValidationErrors, RecommendationEngineErrorFact, ReviewEngineErrorFact, TodayErrorSignal } from '@/error-bank/types';
import { IndexedDbErrorRecordRepository } from './errorRecordRepository';

export const defaultErrorFilters: ErrorFilters = { discipline:'all', subject:'all', category:'all', priority:'all', status:'all', source:'all', query:'', recurringOnly:false, pendingOnly:false };
const normalize = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/\s+/g, ' ').trim();
export function filterErrorRecords(records: ErrorRecord[], f: ErrorFilters) { const q=normalize(f.query); return records.filter((r) => (f.discipline==='all'||r.discipline===f.discipline)&&(f.subject==='all'||r.subject===f.subject)&&(f.category==='all'||r.category===f.category)&&(f.priority==='all'||r.priority===f.priority)&&(f.status==='all'||r.status===f.status)&&(f.source==='all'||r.source===f.source)&&(!f.recurringOnly||r.recurrence>1)&&(!f.pendingOnly||r.status==='active')&&(!q||normalize(`${r.discipline} ${r.subject} ${r.reason} ${r.tags.join(' ')}`).includes(q))); }
export function calculateErrorStats(records: ErrorRecord[]): ErrorBankStats { const active=records.filter((r)=>r.status==='active'); const frequent=(selector:(r:ErrorRecord)=>string)=>{const totals=new Map<string,number>();records.forEach((r)=>totals.set(selector(r),(totals.get(selector(r))??0)+1));return [...totals].sort((a,b)=>b[1]-a[1])[0]?.[0]??'-';}; return {active:active.length,recurring:records.filter((r)=>r.recurrence>1).length,mastered:records.filter((r)=>r.status==='mastered').length,pendingReview:active.filter((r)=>Boolean(r.nextReview)).length,predominantCategory:frequent((r)=>r.category),criticalDiscipline:frequent((r)=>r.discipline)}; }
export const emptyErrorRecordInput: ErrorRecordInput = { discipline:'',subject:'',category:'',context:'',reason:'',correctConcept:'',correctiveAction:'',priority:'',tags:'',notes:'',selectedAnswer:'',source:'Manual',nextReview:'',complementaryNotes:'' };
export function validateErrorRecord(input: ErrorRecordInput, today=new Date()): ErrorRecordValidationErrors { const errors:ErrorRecordValidationErrors={};(['discipline','subject','category','context','reason','correctConcept','correctiveAction','priority'] as const).forEach((key)=>{if(!input[key].trim())errors[key]='Este campo e obrigatorio.';});if(input.nextReview){const date=new Date(`${input.nextReview}T00:00:00`);if(Number.isNaN(date.getTime()))errors.nextReview='Informe uma data valida.';else if(date<new Date(today.getFullYear(),today.getMonth(),today.getDate()))errors.nextReview='A revisao nao pode ser anterior a hoje.';}return errors; }
export function createErrorRecord(input: ErrorRecordInput): ErrorRecord { const now=new Date().toISOString(); return { id:globalThis.crypto?.randomUUID?.()??`error-${Date.now()}`,discipline:input.discipline.trim(),subject:input.subject.trim(),category:input.category.trim(),priority:input.priority||'medium',status:'active',source:input.source.trim()||'Manual',question:input.context.trim(),selectedAnswer:input.selectedAnswer.trim()||'-',correctAnswer:input.correctConcept.trim(),explanation:input.correctConcept.trim(),reason:input.reason.trim(),correctiveAction:input.correctiveAction.trim(),recurrence:1,nextReview:input.nextReview,notes:[input.notes,input.complementaryNotes].filter(Boolean).join(' '),tags:input.tags.split(',').map((tag)=>tag.trim()).filter(Boolean),history:['Registro manual criado'],occurrences:[now],createdAt:now,updatedAt:now,questionBlockId:input.questionBlockId,questionId:input.questionId}; }
export function applyErrorAction(record: ErrorRecord, action: ErrorAction, date?: string): ErrorRecord { const updatedAt=new Date().toISOString(); if(action==='review')return{...record,status:'reviewed',lastReviewedAt:updatedAt,updatedAt,history:[...record.history,'Erro marcado como revisado.']};if(action==='master')return{...record,status:'mastered',updatedAt,history:[...record.history,'Assunto marcado como dominado.']};if(action==='archive')return{...record,status:'archived',updatedAt,history:[...record.history,'Erro arquivado.']};if(action==='recur')return{...record,recurrence:record.recurrence+1,occurrences:[...record.occurrences,updatedAt],status:'active',updatedAt,history:[...record.history,'Nova ocorrencia registrada.']};return{...record,nextReview:date||record.nextReview,updatedAt,history:[...record.history,'Revisao reagendada.']}; }
export function createErrorBankFacts(records: ErrorRecord[]): ErrorBankFacts { return {activeErrors:records.filter((r)=>r.status==='active').length,recurringErrorSubjects:records.filter((r)=>r.recurrence>1).map((r)=>r.subject),pendingReviewIds:records.filter((r)=>r.status==='active'&&Boolean(r.nextReview)).map((r)=>r.id)}; }
export const toReviewFact=(r:ErrorRecord):ReviewEngineErrorFact=>({errorId:r.id,subject:r.subject,nextReview:r.nextReview}); export const toRecommendationFact=(r:ErrorRecord):RecommendationEngineErrorFact=>({errorId:r.id,correctiveAction:r.correctiveAction}); export const toAnalyticsEvent=(r:ErrorRecord):AnalyticsEngineErrorEvent=>({errorId:r.id,category:r.category,recurrence:r.recurrence}); export const toTodaySignal=(r:ErrorRecord):TodayErrorSignal=>({errorId:r.id,correctiveAction:r.correctiveAction});
const repository=new IndexedDbErrorRecordRepository();
export const ErrorBankService={
  getRecords: async()=> (await repository.getAll()).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),
  create: async(input:ErrorRecordInput)=>{const validation=validateErrorRecord(input);if(Object.keys(validation).length)throw new Error('Revise os campos obrigatorios.');const candidate=createErrorRecord(input);const existing=(await repository.getAll()).find((r)=>r.status!=='archived'&&r.discipline===candidate.discipline&&r.subject===candidate.subject&&r.category===candidate.category&&normalize(r.question)===normalize(candidate.question));if(existing){const recurring=applyErrorAction(existing,'recur');await repository.update(recurring);publishLocalDataChange();return {record:recurring,wasDuplicate:true};}await repository.create(candidate);publishLocalDataChange();return {record:candidate,wasDuplicate:false};},
  runAction: async(record:ErrorRecord,action:ErrorAction,date?:string)=>{const updated=applyErrorAction(record,action,date);await repository.update(updated);publishLocalDataChange();return updated;},
};
export * from './errorRecordRepository';
