import { describe, expect, it } from 'vitest';
import { defaultMaterialEstimates, generateDecisionEngineResult, type DecisionEngineInput } from './DecisionEngineService';

const base = (): DecisionEngineInput => ({ now: '2026-07-13T12:00:00.000Z', examDate: '2026-10-11', scheduleItems: [], studySessions: [], questionBlocks: [], errors: [], reviews: [], weeklyGoalMinutes: 900, materialEstimates: defaultMaterialEstimates });
describe('DecisionEngineService', () => {
  it('creates explainable recommendations and preserves input facts', () => { const input = base(); input.reviews = [{ id: 'r1', scheduledAt: '2026-07-09', status: 'pending', estimatedMinutes: 30 } as never]; const snapshot = structuredClone(input); const result = generateDecisionEngineResult(input); expect(result.recommendations[0]).toMatchObject({ ruleId: 'overdue-review', actionRoute: '/revisoes', urgency: 'critical' }); expect(result.recommendations[0]?.evidence.length).toBeGreaterThan(0); expect(input).toEqual(snapshot); });
  it('prioritizes overdue schedule work and today work', () => { const input = base(); input.scheduleItems = [{ id: 'late', disciplineName: 'Governanca', title: 'COBIT', plannedDate: '2026-07-09', activityType: 'PDF', status: 'planned', outsideExamWindow: false, createdAt: '', updatedAt: '' }, { id: 'today', disciplineName: 'Dados', title: 'APO06', plannedDate: '2026-07-13', activityType: 'PDF', status: 'planned', outsideExamWindow: false, createdAt: '', updatedAt: '' }]; const result = generateDecisionEngineResult(input); expect(result.recommendations.map((item) => item.ruleId)).toContain('overdue-schedule'); expect(result.recommendations.map((item) => item.ruleId)).toContain('today-schedule'); });
  it('uses a minimum sample for performance and exposes recurring errors', () => { const input = base(); input.studySessions = [{ id: 's1', date: '2026-07-12', disciplineId: 'd', disciplineName: 'TI', subject: 'Redes', materialType: 'questions', durationMinutes: 20, difficulty: 'moderate', questionsAnswered: 10, correctAnswers: 6, wrongAnswers: 4, notes: '', source: '', status: 'completed', createdAt: '', updatedAt: '' }]; input.errors = [{ id: 'e1', discipline: 'TI', subject: 'Redes', status: 'active', recurrence: 4 } as never]; const result = generateDecisionEngineResult(input); expect(result.recommendations.map((item) => item.ruleId)).toEqual(expect.arrayContaining(['low-performance', 'recurring-error'])); const insufficient = generateDecisionEngineResult({ ...base(), studySessions: [{ ...input.studySessions[0], questionsAnswered: 9 }] }); expect(insufficient.recommendations.map((item) => item.ruleId)).not.toContain('low-performance'); });
  it('limits and orders recommendations inside the engine', () => { const input = base(); input.errors = Array.from({ length: 8 }, (_, index) => ({ id: `e${index}`, discipline: 'TI', subject: `Assunto ${index}`, status: 'active', recurrence: 4 } as never)); const result = generateDecisionEngineResult(input); expect(result.recommendations).toHaveLength(5); expect(result.recommendations.map((item) => item.ruleId)).toContain('recurring-error'); expect(result.recommendations.every((item) => item.evidence.length > 0)).toBe(true); });
  it('does not generate a weekly risk after the goal is met', () => { const input = base(); input.weeklyGoalMinutes = 60; input.studySessions = [{ id: 's', date: '2026-07-13', durationMinutes: 60 } as never]; expect(generateDecisionEngineResult(input).recommendations.map((item) => item.ruleId)).not.toContain('weekly-goal-risk'); });
});
